language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
notifications:
  slack:
    secure: kaSU4dY6seT/uhBv1xB6Rl6wkjEzbNxUNvFu2jkD0tjWEzONwwiwrMjGcVsi/tEeDQGxHOR7UOOk3NCBSRX8WGKRR7NUd/rNVjziGCka+wmwXe8h+3lbpLrJ8xTKvMvJk0e2gPtYvop55aWfxlFlctYUOn7w0YLdirUGh8lbZYfNVS0cLPxvRrMVN0BwUkGVdSfY1MFwkjlZSinu0ldyvb7ywk9/OmhnCa7bPpumWffAHKrwTzLsLEG0DARvgufXb/lawB8P5SGiyDMM0Z+2mz3KmDrDW5xd54WQsB6t6iaAzDzKvSS1eq93hVu/lfwUz6bVlG4V8j6vlJVROh0MCM9rth9wl9Iiqd4mMV8wp7kZHh7YqjrXtYjHPajYLgvmZUXsvVxzPSTyq3mSVpnXkCiaG6pHf+FFPrfeHOe2+TmrSz080Pu/GTW838W7/5NEW/KuFHV76ZPqsnxRPIaYoztqr7s/LVB9pQ+LgSnOSl5vkhMa8xlz7naGJ042mCW8lWzemBGqGiaEEzXJXx9LavFx3QFebI8LF0e3g/9nNLFAWt8Nxq9pscblPJ7V8OHoLdNUxJBqm/25j8RAijLYMjI/zcnHpXJGyP+VRF1kgLZBR5Qw/nP06F9SUGVblc7rwG83wvIb+IQMsiO5tPhD/DudmzPOBmafEuzAGIBYX5I=
    on_success: change
    on_failure: always
deploy:
  provider: heroku
  strategy: git
  app:
    master: thesismarket-api
  api_key:
    secure: Lb1A8zpwvepKTl+Ep4RJE9npC0Msqu0Z5LDnZmmgGCouqfJcb/Y40UL++BDmVGgD08URrJeKRX2ekxrimucir+3lm+Zc3cPGijESvmIXvMXd0RCDoKP+sD0htuoc0Iu/ol7Tea9D934IzOTUbgVYeYbjL7/TnpO88SwHkKyotEOsIYCLw5WSl2JZe2H1RrRQfOMjr6lIcxoqd1DvMcxaZ2Y1kbBDIA1BgdhJ91rMUFXMPu4VaiuSXFZP8wQ13FtR594M9koWoW2CdXyukkin/qRY663UIELC11REeJwQRBusHoHDzQ0cORBAmAKH7SCmDavrm0nJpFFSXc+ffG3VemwDsWSLVWTN4ft1N3zyIAwXecIRRfTLW1k/Az34fJ7ycJlgdfRfjz/aA306HRT4CO8XWl/1rIjRZltZq4yoKbcCPrfKFvT49pW3UX+mCzAvRe9C7fd1nmLpqs5VNOvz8HqVR7FglpFehr1FGcqdu1t4/WvcBvMzZvMtRl023zSzM+oiV957p+CxVpxPbbGIGrQVF4Z8CNK9kyjLGAymBnj2mDr/P3PRbFIUI8ian5BY0EPyVCTwFDz/M70UVhBF20BFMQ9Ol8u84MVjG4fd1UXBPUFgU4IAJI+79e/fUDlocq+OWRHzTVAfdP1g885juUCi7AAQgjcDVYF0lQZOSFM=
